apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-deployment
  labels:
    app: spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
        - name: spa
          image: durbo/books-front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: spa-key
