apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value
  name: spa-service
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: spa
